# justfile

default:
  @just --summary

help:
  @just --list

#alias mb := make-both
#make-both: build-2 create-2 build-2022 create-2022

alias m := make
make-both: build create
  
alias b := build
build:
  podman build -t amazonlinux-toolbox:2022 -f Containerfile .

alias e := enter
enter:
  toolbox enter amazonlinux-toolbox-2022

alias c := create
create:
  toolbox create -c amazonlinux-toolbox-2022 -i amazonlinux-toolbox:2022

alias cu := cleanup
cleanup:
  podman stop amazonlinux-toolbox-2022
  toolbox rm amazonlinux-toolbox-2022
  toolbox rmi amazonlinux-toolbox:2022

alias p := push
push:
  aws ecr-public get-login-password --region us-east-1 | podman login --username AWS --password-stdin public.ecr.aws/l6o8q4o8
  podman tag thimslugga/amazonlinux-toolbox:2022 public.ecr.aws/l6o8q4o8/thimslugga/amazonlinux-toolbox:2022
  podman push public.ecr.aws/l6o8q4o8/thimslugga/amazonlinux-toolbox:2022
