# https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-user-systemd-unit-on-boot/

#FROM public.ecr.aws/amazonlinux/amazonlinux:2023
FROM public.ecr.aws/amazonlinux/amazonlinux:2023-minimal

VOLUME ["/sys/fs/cgroup"]

#ENV container=docker

RUN microdnf install -y systemd ssmtp procps file\
    && microdnf clean all \
    && echo "ForwardToConsole=yes" >> /etc/systemd/journald.conf \
    && systemctl mask console-getty.service getty@tty1.service \
    && mkdir -p /etc/initial-setup.d \
    && mkdir -p /etc/initial-setup.user.d \
    && mkdir -p /etc/start-scripts.d \
    && mkdir -p /etc/start-scripts.user.d \
    && mkdir -p /etc/systemd/user-units

# Add infrastructure to run setup and start scripts
ADD initial-setup.service /etc/systemd/system/initial-setup.service
ADD start-scripts.service /etc/systemd/system/start-scripts.service
ADD systemd-email@.service /etc/systemd/system/systemd-email@.service
ADD initial-setup.sh /etc/initial-setup.sh
ADD start-scripts.sh /etc/start-scripts.sh
ADD systemd-email.sh /etc/systemd-email.sh
ADD 00-setup-user-units.sh /etc/initial-setup.d/00-setup-user-units.sh

#RUN ln -s /usr/lib/systemd/system/systemd-user-sessions.service \
#     /lib/systemd/system/multi-user.target.wants/systemd-user-sessions.service

RUN \
  systemctl enable initial-setup.service \
  && systemctl enable start-scripts.service

#EXPOSE 22/tcp

#RUN systemctl enable sshd.service

ENTRYPOINT ["/usr/sbin/init"]
#CMD ["/usr/sbin/init"]
